// <auto-generated />
using System;
using Bibliotekssystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bibliotekssystem.Data.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20260304175238_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Bibliotekssystem.Core.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "J.R.R. Tolkien",
                            ISBN = "978-91-0-123456-7",
                            IsAvailable = false,
                            PublishedYear = 1954,
                            Title = "Sagan om ringen"
                        },
                        new
                        {
                            Id = 2,
                            Author = "J.R.R. Tolkien",
                            ISBN = "978-91-0-654321-8",
                            IsAvailable = true,
                            PublishedYear = 1937,
                            Title = "Hobbiten"
                        },
                        new
                        {
                            Id = 3,
                            Author = "George Orwell",
                            ISBN = "978-91-0-111111-9",
                            IsAvailable = false,
                            PublishedYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 4,
                            Author = "George Orwell",
                            ISBN = "978-91-0-222222-0",
                            IsAvailable = true,
                            PublishedYear = 1945,
                            Title = "Djurfarmen"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Astrid Lindgren",
                            ISBN = "978-91-0-333333-1",
                            IsAvailable = true,
                            PublishedYear = 1945,
                            Title = "Pippi Långstrump"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Astrid Lindgren",
                            ISBN = "978-91-0-444444-2",
                            IsAvailable = true,
                            PublishedYear = 1973,
                            Title = "Bröderna Lejonhjärta"
                        },
                        new
                        {
                            Id = 7,
                            Author = "August Strindberg",
                            ISBN = "978-91-0-555555-3",
                            IsAvailable = true,
                            PublishedYear = 1879,
                            Title = "Röda rummet"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Hjalmar Söderberg",
                            ISBN = "978-91-0-666666-4",
                            IsAvailable = false,
                            PublishedYear = 1905,
                            Title = "Doktor Glas"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Selma Lagerlöf",
                            ISBN = "978-91-0-777777-5",
                            IsAvailable = true,
                            PublishedYear = 1904,
                            Title = "Herr Arnes penningar"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Selma Lagerlöf",
                            ISBN = "978-91-0-888888-6",
                            IsAvailable = true,
                            PublishedYear = 1891,
                            Title = "Gösta Berlings saga"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Karin Boye",
                            ISBN = "978-91-0-999999-7",
                            IsAvailable = true,
                            PublishedYear = 1940,
                            Title = "Kallocain"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Selma Lagerlöf",
                            ISBN = "978-91-0-101010-8",
                            IsAvailable = false,
                            PublishedYear = 1907,
                            Title = "Nils Holgerssons underbara resa"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Astrid Lindgren",
                            ISBN = "978-91-0-121212-9",
                            IsAvailable = true,
                            PublishedYear = 1954,
                            Title = "Mio, min Mio"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Astrid Lindgren",
                            ISBN = "978-91-0-131313-0",
                            IsAvailable = true,
                            PublishedYear = 1981,
                            Title = "Ronja Rövardotter"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Hjalmar Bergman",
                            ISBN = "978-91-0-141414-1",
                            IsAvailable = true,
                            PublishedYear = 1919,
                            Title = "Markurells i Wadköping"
                        });
                });

            modelBuilder.Entity("Bibliotekssystem.Core.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LoanDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("MemberId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            DueDate = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 3,
                            DueDate = new DateTime(2025, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookId = 8,
                            DueDate = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 5
                        },
                        new
                        {
                            Id = 4,
                            BookId = 12,
                            DueDate = new DateTime(2025, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 3
                        },
                        new
                        {
                            Id = 5,
                            BookId = 2,
                            DueDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 1,
                            ReturnDate = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            BookId = 5,
                            DueDate = new DateTime(2025, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 4,
                            ReturnDate = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            BookId = 7,
                            DueDate = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 6,
                            ReturnDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            BookId = 4,
                            DueDate = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 7,
                            ReturnDate = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Bibliotekssystem.Core.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MemberSince")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "anna@example.com",
                            MemberId = "M001",
                            MemberSince = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Anna Svensson"
                        },
                        new
                        {
                            Id = 2,
                            Email = "erik@example.com",
                            MemberId = "M002",
                            MemberSince = new DateTime(2023, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Erik Johansson"
                        },
                        new
                        {
                            Id = 3,
                            Email = "maria@example.com",
                            MemberId = "M003",
                            MemberSince = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Maria Andersson"
                        },
                        new
                        {
                            Id = 4,
                            Email = "karl@example.com",
                            MemberId = "M004",
                            MemberSince = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Karl Pettersson"
                        },
                        new
                        {
                            Id = 5,
                            Email = "lisa@example.com",
                            MemberId = "M005",
                            MemberSince = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lisa Nilsson"
                        },
                        new
                        {
                            Id = 6,
                            Email = "oscar@example.com",
                            MemberId = "M006",
                            MemberSince = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Oscar Lindqvist"
                        },
                        new
                        {
                            Id = 7,
                            Email = "emma@example.com",
                            MemberId = "M007",
                            MemberSince = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Emma Bergström"
                        },
                        new
                        {
                            Id = 8,
                            Email = "gustav@example.com",
                            MemberId = "M008",
                            MemberSince = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gustav Eriksson"
                        });
                });

            modelBuilder.Entity("Bibliotekssystem.Core.Models.Loan", b =>
                {
                    b.HasOne("Bibliotekssystem.Core.Models.Book", "Book")
                        .WithMany("Loans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bibliotekssystem.Core.Models.Member", "Member")
                        .WithMany("Loans")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Bibliotekssystem.Core.Models.Book", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("Bibliotekssystem.Core.Models.Member", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
